version: "2"
run:
  build-tags:
    - e2e
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - containedctx
    - copyloopvar
    - dogsled
    - errcheck
    - ginkgolinter
    - goconst
    - gocritic
    - godot
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - appendAssign
        - dupImport
        - evalOrder
        - ifElseChain
        - octalLiteral
        - regexpSimplify
        - sloppyReassign
        - truncateCmp
        - typeDefFirst
        - unnamedResult
        - unnecessaryDefer
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - experimental
    godot:
      scope: toplevel
      exclude:
        - ^ \+.*
        - ^ ANCHOR.*
    gosec:
      excludes:
        - G307
        - G108
    importas:
      alias:
        - pkg: k8s.io/api/core/v1
          alias: corev1
        - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
          alias: apiextensionsv1
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: apierrors
        - pkg: k8s.io/apimachinery/pkg/util/errors
          alias: kerrors
        - pkg: sigs.k8s.io/controller-runtime
          alias: ctrl
        - pkg: sigs.k8s.io/cluster-api/api/v1alpha3
          alias: clusterv1alpha3
        - pkg: sigs.k8s.io/cluster-api/api/v1alpha4
          alias: clusterv1alpha4
        - pkg: sigs.k8s.io/cluster-api/api/v1beta1
          alias: clusterv1
        - pkg: sigs.k8s.io/cluster-api/exp/ipamapi/v1alpha1
          alias: ipamv1
      no-unaliased: true
    nolintlint:
      require-specific: true
      allow-unused: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        text: 'exported: exported method .*\.(Reconcile|SetupWithManager|SetupWebhookWithManager) should have comment or be unexported'
      - linters:
          - errcheck
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
      - linters:
          - revive
        text: exported (method|function|type|const) (.+) should have comment or be unexported
        source: (func|type).*Fake.*
      - linters:
          - revive
        path: fake_\.go
        text: exported (method|function|type|const) (.+) should have comment or be unexported
      - linters:
          - revive
        path: cmd/clusterctl/internal/test/providers.*.go
        text: exported (method|function|type|const) (.+) should have comment or be unexported
      - linters:
          - revive
        path: (framework|e2e)/.*.go
        text: exported (method|function|type|const) (.+) should have comment or be unexported
      - linters:
          - unparam
        text: always receives
      - path: _test\.go
        text: should not use dot imports
      - path: (framework|e2e)/.*.go
        text: should not use dot imports
      - path: _test\.go
        text: cyclomatic complexity
      - linters:
          - gocritic
        text: 'appendAssign: append result not assigned to the same slice'
      - linters:
          - ifshort
        path: controllers/mdutil/util.go
        text: variable .* is only used in the if-statement
      - linters:
          - staticcheck
        path: .*(api|types)\/.*\/conversion.*\.go$
        text: 'SA1019: in.(.+) is deprecated'
      - linters:
          - revive
        path: .*(api|types|test)\/.*\/conversion.*\.go$
        text: exported (method|function|type|const) (.+) should have comment or be unexported
      - linters:
          - revive
        path: .*(api|types|test)\/.*\/conversion.*\.go$
        text: 'var-naming: don''t use underscores in Go names;'
      - linters:
          - revive
        path: .*(api|types)\/.*\/conversion.*\.go$
        text: 'receiver-naming: receiver name'
      - linters:
          - staticcheck
        path: .*(api|types|test)\/.*\/conversion.*\.go$
        text: 'ST1003: should not use underscores in Go names;'
      - linters:
          - staticcheck
        path: .*(api|types)\/.*\/conversion.*\.go$
        text: 'ST1016: methods on the same type should have the same receiver name'
      - linters:
          - ifshort
        path: ^internal/controllers/machine/machine_controller\.go$
        text: variable 'isDeleteNodeAllowed' is only used in the if-statement.*
      - linters:
          - ifshort
        path: ^controlplane/kubeadm/internal/workload_cluster_conditions\.go$
        text: variable 'kcpMachinesWithErrors' is only used in the if-statement.*
      - linters:
          - gocritic
        path: _test\.go
        text: 'deferInLoop: Possible resource leak, ''defer'' is called in the ''for'' loop'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
