# permissions for end users to view infobloxinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: infobloxinstance-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-ipam-provider-infoblox
    app.kubernetes.io/part-of: cluster-api-ipam-provider-infoblox
    app.kubernetes.io/managed-by: kustomize
  name: infobloxinstance-viewer-role
rules:
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - infobloxinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - infobloxinstances/status
  verbs:
  - get
