apiVersion: ipam.cluster.x-k8s.io/v1alpha1
kind: InfobloxInstance
metadata:
  labels:
    app.kubernetes.io/name: infobloxinstance
    app.kubernetes.io/instance: infobloxinstance-sample
    app.kubernetes.io/part-of: cluster-api-ipam-provider-infoblox
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-api-ipam-provider-infoblox
  name: infobloxinstance-sample
spec:
  # TODO(user): Add fields here
