//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1alpha2 "github.com/telekom/cluster-api-ipam-provider-infoblox/api/v1alpha2"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*InfobloxIPPool)(nil), (*v1alpha2.InfobloxIPPool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfobloxIPPool_To_v1alpha2_InfobloxIPPool(a.(*InfobloxIPPool), b.(*v1alpha2.InfobloxIPPool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.InfobloxIPPool)(nil), (*InfobloxIPPool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_InfobloxIPPool_To_v1alpha1_InfobloxIPPool(a.(*v1alpha2.InfobloxIPPool), b.(*InfobloxIPPool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfobloxIPPoolList)(nil), (*v1alpha2.InfobloxIPPoolList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfobloxIPPoolList_To_v1alpha2_InfobloxIPPoolList(a.(*InfobloxIPPoolList), b.(*v1alpha2.InfobloxIPPoolList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.InfobloxIPPoolList)(nil), (*InfobloxIPPoolList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_InfobloxIPPoolList_To_v1alpha1_InfobloxIPPoolList(a.(*v1alpha2.InfobloxIPPoolList), b.(*InfobloxIPPoolList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfobloxIPPoolSpec)(nil), (*v1alpha2.InfobloxIPPoolSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfobloxIPPoolSpec_To_v1alpha2_InfobloxIPPoolSpec(a.(*InfobloxIPPoolSpec), b.(*v1alpha2.InfobloxIPPoolSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.InfobloxIPPoolSpec)(nil), (*InfobloxIPPoolSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_InfobloxIPPoolSpec_To_v1alpha1_InfobloxIPPoolSpec(a.(*v1alpha2.InfobloxIPPoolSpec), b.(*InfobloxIPPoolSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfobloxIPPoolStatus)(nil), (*v1alpha2.InfobloxIPPoolStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfobloxIPPoolStatus_To_v1alpha2_InfobloxIPPoolStatus(a.(*InfobloxIPPoolStatus), b.(*v1alpha2.InfobloxIPPoolStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.InfobloxIPPoolStatus)(nil), (*InfobloxIPPoolStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_InfobloxIPPoolStatus_To_v1alpha1_InfobloxIPPoolStatus(a.(*v1alpha2.InfobloxIPPoolStatus), b.(*InfobloxIPPoolStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfobloxInstance)(nil), (*v1alpha2.InfobloxInstance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfobloxInstance_To_v1alpha2_InfobloxInstance(a.(*InfobloxInstance), b.(*v1alpha2.InfobloxInstance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.InfobloxInstance)(nil), (*InfobloxInstance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_InfobloxInstance_To_v1alpha1_InfobloxInstance(a.(*v1alpha2.InfobloxInstance), b.(*InfobloxInstance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfobloxInstanceList)(nil), (*v1alpha2.InfobloxInstanceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfobloxInstanceList_To_v1alpha2_InfobloxInstanceList(a.(*InfobloxInstanceList), b.(*v1alpha2.InfobloxInstanceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.InfobloxInstanceList)(nil), (*InfobloxInstanceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_InfobloxInstanceList_To_v1alpha1_InfobloxInstanceList(a.(*v1alpha2.InfobloxInstanceList), b.(*InfobloxInstanceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfobloxInstanceSpec)(nil), (*v1alpha2.InfobloxInstanceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfobloxInstanceSpec_To_v1alpha2_InfobloxInstanceSpec(a.(*InfobloxInstanceSpec), b.(*v1alpha2.InfobloxInstanceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.InfobloxInstanceSpec)(nil), (*InfobloxInstanceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_InfobloxInstanceSpec_To_v1alpha1_InfobloxInstanceSpec(a.(*v1alpha2.InfobloxInstanceSpec), b.(*InfobloxInstanceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfobloxInstanceStatus)(nil), (*v1alpha2.InfobloxInstanceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfobloxInstanceStatus_To_v1alpha2_InfobloxInstanceStatus(a.(*InfobloxInstanceStatus), b.(*v1alpha2.InfobloxInstanceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.InfobloxInstanceStatus)(nil), (*InfobloxInstanceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_InfobloxInstanceStatus_To_v1alpha1_InfobloxInstanceStatus(a.(*v1alpha2.InfobloxInstanceStatus), b.(*InfobloxInstanceStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_InfobloxIPPool_To_v1alpha2_InfobloxIPPool(in *InfobloxIPPool, out *v1alpha2.InfobloxIPPool, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_InfobloxIPPoolSpec_To_v1alpha2_InfobloxIPPoolSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_InfobloxIPPoolStatus_To_v1alpha2_InfobloxIPPoolStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_InfobloxIPPool_To_v1alpha2_InfobloxIPPool is an autogenerated conversion function.
func Convert_v1alpha1_InfobloxIPPool_To_v1alpha2_InfobloxIPPool(in *InfobloxIPPool, out *v1alpha2.InfobloxIPPool, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfobloxIPPool_To_v1alpha2_InfobloxIPPool(in, out, s)
}

func autoConvert_v1alpha2_InfobloxIPPool_To_v1alpha1_InfobloxIPPool(in *v1alpha2.InfobloxIPPool, out *InfobloxIPPool, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_InfobloxIPPoolSpec_To_v1alpha1_InfobloxIPPoolSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_InfobloxIPPoolStatus_To_v1alpha1_InfobloxIPPoolStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_InfobloxIPPool_To_v1alpha1_InfobloxIPPool is an autogenerated conversion function.
func Convert_v1alpha2_InfobloxIPPool_To_v1alpha1_InfobloxIPPool(in *v1alpha2.InfobloxIPPool, out *InfobloxIPPool, s conversion.Scope) error {
	return autoConvert_v1alpha2_InfobloxIPPool_To_v1alpha1_InfobloxIPPool(in, out, s)
}

func autoConvert_v1alpha1_InfobloxIPPoolList_To_v1alpha2_InfobloxIPPoolList(in *InfobloxIPPoolList, out *v1alpha2.InfobloxIPPoolList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha2.InfobloxIPPool)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_InfobloxIPPoolList_To_v1alpha2_InfobloxIPPoolList is an autogenerated conversion function.
func Convert_v1alpha1_InfobloxIPPoolList_To_v1alpha2_InfobloxIPPoolList(in *InfobloxIPPoolList, out *v1alpha2.InfobloxIPPoolList, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfobloxIPPoolList_To_v1alpha2_InfobloxIPPoolList(in, out, s)
}

func autoConvert_v1alpha2_InfobloxIPPoolList_To_v1alpha1_InfobloxIPPoolList(in *v1alpha2.InfobloxIPPoolList, out *InfobloxIPPoolList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]InfobloxIPPool)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha2_InfobloxIPPoolList_To_v1alpha1_InfobloxIPPoolList is an autogenerated conversion function.
func Convert_v1alpha2_InfobloxIPPoolList_To_v1alpha1_InfobloxIPPoolList(in *v1alpha2.InfobloxIPPoolList, out *InfobloxIPPoolList, s conversion.Scope) error {
	return autoConvert_v1alpha2_InfobloxIPPoolList_To_v1alpha1_InfobloxIPPoolList(in, out, s)
}

func autoConvert_v1alpha1_InfobloxIPPoolSpec_To_v1alpha2_InfobloxIPPoolSpec(in *InfobloxIPPoolSpec, out *v1alpha2.InfobloxIPPoolSpec, s conversion.Scope) error {
	out.InstanceRef = in.InstanceRef
	out.Subnet = in.Subnet
	out.NetworkView = in.NetworkView
	out.DNSZone = in.DNSZone
	return nil
}

// Convert_v1alpha1_InfobloxIPPoolSpec_To_v1alpha2_InfobloxIPPoolSpec is an autogenerated conversion function.
func Convert_v1alpha1_InfobloxIPPoolSpec_To_v1alpha2_InfobloxIPPoolSpec(in *InfobloxIPPoolSpec, out *v1alpha2.InfobloxIPPoolSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfobloxIPPoolSpec_To_v1alpha2_InfobloxIPPoolSpec(in, out, s)
}

func autoConvert_v1alpha2_InfobloxIPPoolSpec_To_v1alpha1_InfobloxIPPoolSpec(in *v1alpha2.InfobloxIPPoolSpec, out *InfobloxIPPoolSpec, s conversion.Scope) error {
	out.InstanceRef = in.InstanceRef
	out.Subnet = in.Subnet
	out.NetworkView = in.NetworkView
	out.DNSZone = in.DNSZone
	return nil
}

// Convert_v1alpha2_InfobloxIPPoolSpec_To_v1alpha1_InfobloxIPPoolSpec is an autogenerated conversion function.
func Convert_v1alpha2_InfobloxIPPoolSpec_To_v1alpha1_InfobloxIPPoolSpec(in *v1alpha2.InfobloxIPPoolSpec, out *InfobloxIPPoolSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_InfobloxIPPoolSpec_To_v1alpha1_InfobloxIPPoolSpec(in, out, s)
}

func autoConvert_v1alpha1_InfobloxIPPoolStatus_To_v1alpha2_InfobloxIPPoolStatus(in *InfobloxIPPoolStatus, out *v1alpha2.InfobloxIPPoolStatus, s conversion.Scope) error {
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_InfobloxIPPoolStatus_To_v1alpha2_InfobloxIPPoolStatus is an autogenerated conversion function.
func Convert_v1alpha1_InfobloxIPPoolStatus_To_v1alpha2_InfobloxIPPoolStatus(in *InfobloxIPPoolStatus, out *v1alpha2.InfobloxIPPoolStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfobloxIPPoolStatus_To_v1alpha2_InfobloxIPPoolStatus(in, out, s)
}

func autoConvert_v1alpha2_InfobloxIPPoolStatus_To_v1alpha1_InfobloxIPPoolStatus(in *v1alpha2.InfobloxIPPoolStatus, out *InfobloxIPPoolStatus, s conversion.Scope) error {
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha2_InfobloxIPPoolStatus_To_v1alpha1_InfobloxIPPoolStatus is an autogenerated conversion function.
func Convert_v1alpha2_InfobloxIPPoolStatus_To_v1alpha1_InfobloxIPPoolStatus(in *v1alpha2.InfobloxIPPoolStatus, out *InfobloxIPPoolStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_InfobloxIPPoolStatus_To_v1alpha1_InfobloxIPPoolStatus(in, out, s)
}

func autoConvert_v1alpha1_InfobloxInstance_To_v1alpha2_InfobloxInstance(in *InfobloxInstance, out *v1alpha2.InfobloxInstance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_InfobloxInstanceSpec_To_v1alpha2_InfobloxInstanceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_InfobloxInstanceStatus_To_v1alpha2_InfobloxInstanceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_InfobloxInstance_To_v1alpha2_InfobloxInstance is an autogenerated conversion function.
func Convert_v1alpha1_InfobloxInstance_To_v1alpha2_InfobloxInstance(in *InfobloxInstance, out *v1alpha2.InfobloxInstance, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfobloxInstance_To_v1alpha2_InfobloxInstance(in, out, s)
}

func autoConvert_v1alpha2_InfobloxInstance_To_v1alpha1_InfobloxInstance(in *v1alpha2.InfobloxInstance, out *InfobloxInstance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_InfobloxInstanceSpec_To_v1alpha1_InfobloxInstanceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_InfobloxInstanceStatus_To_v1alpha1_InfobloxInstanceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_InfobloxInstance_To_v1alpha1_InfobloxInstance is an autogenerated conversion function.
func Convert_v1alpha2_InfobloxInstance_To_v1alpha1_InfobloxInstance(in *v1alpha2.InfobloxInstance, out *InfobloxInstance, s conversion.Scope) error {
	return autoConvert_v1alpha2_InfobloxInstance_To_v1alpha1_InfobloxInstance(in, out, s)
}

func autoConvert_v1alpha1_InfobloxInstanceList_To_v1alpha2_InfobloxInstanceList(in *InfobloxInstanceList, out *v1alpha2.InfobloxInstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha2.InfobloxInstance)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_InfobloxInstanceList_To_v1alpha2_InfobloxInstanceList is an autogenerated conversion function.
func Convert_v1alpha1_InfobloxInstanceList_To_v1alpha2_InfobloxInstanceList(in *InfobloxInstanceList, out *v1alpha2.InfobloxInstanceList, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfobloxInstanceList_To_v1alpha2_InfobloxInstanceList(in, out, s)
}

func autoConvert_v1alpha2_InfobloxInstanceList_To_v1alpha1_InfobloxInstanceList(in *v1alpha2.InfobloxInstanceList, out *InfobloxInstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]InfobloxInstance)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha2_InfobloxInstanceList_To_v1alpha1_InfobloxInstanceList is an autogenerated conversion function.
func Convert_v1alpha2_InfobloxInstanceList_To_v1alpha1_InfobloxInstanceList(in *v1alpha2.InfobloxInstanceList, out *InfobloxInstanceList, s conversion.Scope) error {
	return autoConvert_v1alpha2_InfobloxInstanceList_To_v1alpha1_InfobloxInstanceList(in, out, s)
}

func autoConvert_v1alpha1_InfobloxInstanceSpec_To_v1alpha2_InfobloxInstanceSpec(in *InfobloxInstanceSpec, out *v1alpha2.InfobloxInstanceSpec, s conversion.Scope) error {
	out.Host = in.Host
	out.Port = in.Port
	out.WAPIVersion = in.WAPIVersion
	out.CredentialsSecretRef = in.CredentialsSecretRef
	out.DefaultNetworkView = in.DefaultNetworkView
	out.InsecureSkipTLSVerify = in.InsecureSkipTLSVerify
	return nil
}

// Convert_v1alpha1_InfobloxInstanceSpec_To_v1alpha2_InfobloxInstanceSpec is an autogenerated conversion function.
func Convert_v1alpha1_InfobloxInstanceSpec_To_v1alpha2_InfobloxInstanceSpec(in *InfobloxInstanceSpec, out *v1alpha2.InfobloxInstanceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfobloxInstanceSpec_To_v1alpha2_InfobloxInstanceSpec(in, out, s)
}

func autoConvert_v1alpha2_InfobloxInstanceSpec_To_v1alpha1_InfobloxInstanceSpec(in *v1alpha2.InfobloxInstanceSpec, out *InfobloxInstanceSpec, s conversion.Scope) error {
	out.Host = in.Host
	out.Port = in.Port
	out.WAPIVersion = in.WAPIVersion
	out.CredentialsSecretRef = in.CredentialsSecretRef
	out.DefaultNetworkView = in.DefaultNetworkView
	out.InsecureSkipTLSVerify = in.InsecureSkipTLSVerify
	return nil
}

// Convert_v1alpha2_InfobloxInstanceSpec_To_v1alpha1_InfobloxInstanceSpec is an autogenerated conversion function.
func Convert_v1alpha2_InfobloxInstanceSpec_To_v1alpha1_InfobloxInstanceSpec(in *v1alpha2.InfobloxInstanceSpec, out *InfobloxInstanceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_InfobloxInstanceSpec_To_v1alpha1_InfobloxInstanceSpec(in, out, s)
}

func autoConvert_v1alpha1_InfobloxInstanceStatus_To_v1alpha2_InfobloxInstanceStatus(in *InfobloxInstanceStatus, out *v1alpha2.InfobloxInstanceStatus, s conversion.Scope) error {
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_InfobloxInstanceStatus_To_v1alpha2_InfobloxInstanceStatus is an autogenerated conversion function.
func Convert_v1alpha1_InfobloxInstanceStatus_To_v1alpha2_InfobloxInstanceStatus(in *InfobloxInstanceStatus, out *v1alpha2.InfobloxInstanceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfobloxInstanceStatus_To_v1alpha2_InfobloxInstanceStatus(in, out, s)
}

func autoConvert_v1alpha2_InfobloxInstanceStatus_To_v1alpha1_InfobloxInstanceStatus(in *v1alpha2.InfobloxInstanceStatus, out *InfobloxInstanceStatus, s conversion.Scope) error {
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha2_InfobloxInstanceStatus_To_v1alpha1_InfobloxInstanceStatus is an autogenerated conversion function.
func Convert_v1alpha2_InfobloxInstanceStatus_To_v1alpha1_InfobloxInstanceStatus(in *v1alpha2.InfobloxInstanceStatus, out *InfobloxInstanceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_InfobloxInstanceStatus_To_v1alpha1_InfobloxInstanceStatus(in, out, s)
}
