name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      image_tags:
        description: 'Comma-separated list of image tags to push'
        required: true
        type: string
      labels:
        description: 'Optional comma-separated list of labels'
        required: false
        type: string
      build_args:
        description: 'Optional newline-separated build args'
        required: false
        type: string

jobs:
  build-image:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v6.0.2
        with:
          go-version-file: go.mod

      - name: Create Docker Licenses Report
        run: make docker-licenses

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.11.1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ${{ inputs.image_tags }}
          labels: ${{ inputs.labels }}
          build-args: ${{ inputs.build_args }}
