name: Build Container Image

on:
  push:
    branches:
      - main

jobs:
  main-image:
    name: build "main" image
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.24'
      
      - name: Create Licenses Report
        run: |
          make licenses-report
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
      - uses: docker/setup-buildx-action@v3.11.1

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ghcr.io/telekom/cluster-api-ipam-provider-infoblox:main
