name: Build Container Image

on:
  push:
    branches:
      - main

jobs:
  main-image:
    uses: ./.github/workflows/build-image.yaml
    with:
      image_tags: ghcr.io/telekom/cluster-api-ipam-provider-infoblox:main
