name: Create Draft Release

on:
  push:
    tags:
      - 'v*'

jobs:
  draft_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v6.0.2
        with:
          go-version-file: go.mod
      - name: Create Release Artifacts
        run: make release
      - name: Create Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        with:
          draft: true
          files: out/ipam-infoblox/${{ github.ref_name }}/*.*

  extract-meta:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      ldflags: ${{ steps.version_info.outputs.LDFLAGS }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.9.0
        id: meta
        with:
          images: ghcr.io/telekom/cluster-api-ipam-provider-infoblox
      - id: version_info
        run: echo "LDFLAGS=$(hack/version.sh)" >> $GITHUB_OUTPUT

  release_image:
    permissions:
      packages: write
    needs: extract-meta
    uses: ./.github/workflows/build-image.yaml
    with:
      image_tags: ${{ needs.extract-meta.outputs.tags }}
      labels: ${{ needs.extract-meta.outputs.labels }}
      build_args: |
        ldflags=${{ needs.extract-meta.outputs.ldflags }}
