name: Create Draft Release

on:
  push:
    tags:
      - 'v*'

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: '^1.24'
      - name: Create Release Artifacts
        run: make release
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: out/*.*

  extract-meta:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      ldflags: ${{ steps.version_info.outputs.LDFLAGS }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5.5.1
        id: meta
        with:
          images: ghcr.io/telekom/cluster-api-ipam-provider-infoblox
      - id: version_info
        run: echo "LDFLAGS=$(hack/version.sh)" >> $GITHUB_OUTPUT

  release_image:
    needs: extract-meta
    uses: ./.github/workflows/build-image.yaml
    with:
      image_tags: ${{ needs.extract-meta.outputs.tags }}
      labels: ${{ needs.extract-meta.outputs.labels }}
      build_args: |
        ldflags=${{ needs.extract-meta.outputs.ldflags }}
